language: node_js

os:
  - linux
  - osx

node_js:
  - '11'
  - '12'
  - 'node' # latest stable Node.js release

notifications:
  email:
    on_success: never
    on_failure: always
script: npm run build:prod
